Repository canonical/ubuntu-server-documentation, pull requests merged in 2025-06, with the labels that each got.

#280 Added 5 definitions for words starting with A
  reference/glossary.rst
Labels: review: technical, content: new, size: S

#289 gnutls.md: clarify that /etc/gnutls/config exists after Noble
  explanation/crypto/gnutls.md
Labels: code: no-code, review: wording, content: edit/update, size: S

#307 gitolite: rewrite for current configuration and best practices
  how-to/backups/install-gitolite.md
  reference/glossary.md
Labels: review: wording, content: edit/update, size: M
